# This workflow adds the necessary assets to every release
# For more details, visit https://github.com/BSData/publish-catpkg
name: publish catpkg
on:
  release:
    types: [published, edited]
jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BSData/publish-catpkg@v1
