name: release
on:
  push:
    branches:
      - master
jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        uses: actions/github-script@v6
        id: create_release
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: 'phnks',
              repo: 'wh40k-kenosis',
              tag_name: 'v${{ github.run_id }}',
              name: 'Latest Release',
              body: ''
            })
            core.setOutput('tag_name', release.tag_name)
            core.setOutput('name', release.name)
            core.setOutput('html_url', release.html_url)
